version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    container_name: portfolio
    command: sh -c "pnpm --filter web start -- -H 0.0.0.0 -p 4000"
    ports:
      - "4001:4000"
    restart: always
    networks:
      - web-network

networks:
  web-network:
    external: true
