services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    ports:
      - "3500:3100"
    env_file:
      - apps/web/.env
