sservices:
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    restart: unless-stopped
    ports:
      - "4001:4000"
    restart: always
    networks:
      - web-network

networks:
  web-network:
    external: true
